### PR TITLE
Social integration

### PR DESCRIPTION
**Pull request by lkpttn**
Adds social integration screens and updates maps. New invite screen, invite flow. Removes codes from registration process and add's social logins. Connecting accounts added to settings screen. Adds App Export Sheet to repo.

### CODE REVIEW

**Comment by aaronschachter** [comment]
@lkpttn `Join Celeb Campaign.png` has both a back button and a X button. which one should it be?

**Comment by aaronschachter** [comment]
@jonuy How do we find the Campaigns that should appear for the Celebrity campaign section?

**Comment by aaronschachter** [comment]
@lkpttn As I'm beginning to think about displaying Reportback Items in the iOS app, i've noticed that on the Campaign Detail, the reportback items display the campaign title, which looks like the link to the campaign. Is this intentional, or should they not be displayed on the campaign detail?

Update: Created #59 for discussion (or to commit correction against)

**Comment by jonuy** [comment]
The X and the back button are a error, I'll push up a change to that and the copy changes to the group page. - Luke

**Comment by aaronschachter** [comment]
@lkpttn Whats the status on this, should it be merged? Working currently on Campaign Detail

**Pull request merged**
