### PR TITLE
Updated Hub page designs

### PR DESCRIPTION
**Pull request by lkpttn**
Updates to readme and hub page designs.

### CODE REVIEW

**Comment by aaronschachter** [comment]
This looks okay, but I am confused as to what the "Been There Done Good" section is for. I was under the assumption that's for the campaigns you've completed and that current is campaigns you haven't reported back on yet.

**Comment by lkpttn** [comment]
Been There, Done Good is for campaigns that are completed in past months. So everything for August would be current, and everything completed from July has moved into Been There, Done Good. Currently there's no limit to how many campaigns back we'll store there.

**Comment by aaronschachter** [comment]
@lkpttn Do the campaigns in "Been There Done Good" link anywhere? or its just a static list? The plan in iOS, at least, has been to only display current campaigns.

**Comment by aaronschachter** [comment]
@lkpttn Also two more questions:
1.  In the public hub, the "Currently Doing" header is removed. Is this intentional?
2. In the self hub: third campaign -- is the plus icon in "friends" intentional?

**Comment by lkpttn** [comment]
1 - Yes, no header in the public hub.

2 - Yes, it has the same functionality as the Invite Friends button. Mostly an aesthetic choice, without a block like the friends area the campaigns look a lot worse.

**Comment by jonuy** [comment]
Just gonna chime in on the "Been There Done Good" section and how that data gets stored -- you hopefully won't have to actually save any of that campaign data on the app. The campaigns you've reported back on should be saved to your user profile which you can get from Northstar. And if that itself doesn't already come along with the campaign info, you'll at least have the campaign id that you can then use to query Phoenix.

**Comment by aaronschachter** [comment]
[The wireframe](https://raw.githubusercontent.com/DoSomething/product/master/LetsDoThis/SpiderProfile.jpg) suggests "Should be User's Reportback image as cover" and doesn't seem to link anywhere.

Which sounds like it could be done if we could query a User's Reportback Items, but the trick would be filtering out any Reportbacks for current Campaigns.

@lkpttn Is this still the desired behavior? This section doesn't link anywhere?

**Comment by lkpttn** [comment]
That is true, just showing you the old pic.

**Pull request merged**
